### ISSUE TITLE
CWL output a directory (cwlrunner)

### ISSUE THREAD

**Issue by JJAlmagro** [kmavrommatis/cwl-tes#3]
When trying to output a whole directory as the final output of the cwl pipeline, the cwlrunner gives the following error:
```
ERROR[0m [31mUnhandled error, try again with --debug for more information:
  [Errno 30] Read-only file system: '/opt/cwl-tes/tumor_fa'
```
but outputting files only works correctly.

Output definition of a directory:
```
  - id: output_reads
    outputSource:
      - convert_readnames/output_reads
    type: Directory
```

Output definition of a file:
```
  - id: fastq_R2
    outputSource:
      - convert_readnames/fastq_R2
    type: File
```
